### ISSUE TITLE
Aarch64 compile inline asm error: unexpected token in argument list

### ISSUE THREAD

**Issue by plaurent** [gnustep/libobjc2#14] opened 2015-12-31 02:07 UTC
I'm running Debian GNU/Linux 8 on a Qualcomm/Arrow Dragonboard 410C and am having trouble compiling libobjc2.

I'm using commit 2ea11117a392646d960f1e861494e2f27873b15b, and Clang 3.7 was apt-gotten.

```
linaro@linaro-alip:~/libobjc2/build$ uname -a
Linux linaro-alip 4.2.4-linaro-lt-qcom #1 SMP PREEMPT Fri Dec 4 12:42:30 UTC 2015 aarch64 GNU/Linux
```

Here is the output of make.

```
Scanning dependencies of target objc
[  1%] Building C object CMakeFiles/objc.dir/abi_version.c.o
[  2%] Building C object CMakeFiles/objc.dir/alias_table.c.o
[  3%] Building C object CMakeFiles/objc.dir/block_to_imp.c.o
[  4%] Building C object CMakeFiles/objc.dir/caps.c.o
[  5%] Building C object CMakeFiles/objc.dir/category_loader.c.o
[  6%] Building C object CMakeFiles/objc.dir/class_table.c.o
[  7%] Building C object CMakeFiles/objc.dir/dtable.c.o
[  8%] Building C object CMakeFiles/objc.dir/eh_personality.c.o
[  9%] Building C object CMakeFiles/objc.dir/encoding2.c.o
[ 10%] Building C object CMakeFiles/objc.dir/hash_table.c.o
[ 11%] Building C object CMakeFiles/objc.dir/hooks.c.o
[ 12%] Building C object CMakeFiles/objc.dir/ivar.c.o
[ 13%] Building C object CMakeFiles/objc.dir/legacy_malloc.c.o
[ 14%] Building C object CMakeFiles/objc.dir/loader.c.o
[ 15%] Building CXX object CMakeFiles/objc.dir/mutation.m.o
[ 16%] Building C object CMakeFiles/objc.dir/protocol.c.o
[ 17%] Building C object CMakeFiles/objc.dir/runtime.c.o
[ 18%] Building C object CMakeFiles/objc.dir/sarray2.c.o
[ 19%] Building C object CMakeFiles/objc.dir/selector_table.c.o
[ 20%] Building C object CMakeFiles/objc.dir/sendmsg2.c.o
[ 21%] Building C object CMakeFiles/objc.dir/statics_loader.c.o
[ 22%] Building C object CMakeFiles/objc.dir/toydispatch.c.o
[ 23%] Building ASM object CMakeFiles/objc.dir/block_trampolines.S.o
[ 25%] Building ASM object CMakeFiles/objc.dir/objc_msgSend.S.o
[ 26%] Building C object CMakeFiles/objc.dir/NSBlocks.m.o
[ 27%] Building C object CMakeFiles/objc.dir/Protocol2.m.o
[ 28%] Building C object CMakeFiles/objc.dir/arc.m.o
[ 29%] Building C object CMakeFiles/objc.dir/associate.m.o
[ 30%] Building C object CMakeFiles/objc.dir/blocks_runtime.m.o
[ 31%] Building C object CMakeFiles/objc.dir/properties.m.o
[ 32%] Building C object CMakeFiles/objc.dir/gc_none.c.o
Linking C shared library libobjc.so
[ 32%] Built target objc
Scanning dependencies of target objcxx
[ 33%] Building CXX object CMakeFiles/objcxx.dir/objcxx_eh.cc.o
Linking C shared library libobjcxx.so
[ 33%] Built target objcxx
Scanning dependencies of target AllocatePair
[ 34%] Building CXX object Test/CMakeFiles/AllocatePair.dir/AllocatePair.m.o
Linking C executable AllocatePair
[ 34%] Built target AllocatePair
Scanning dependencies of target AllocatePair_optimised
[ 35%] Building CXX object Test/CMakeFiles/AllocatePair_optimised.dir/AllocatePair.m.o
Linking C executable AllocatePair_optimised
[ 35%] Built target AllocatePair_optimised
Scanning dependencies of target AssociatedObject
[ 36%] Building CXX object Test/CMakeFiles/AssociatedObject.dir/AssociatedObject.m.o
Linking C executable AssociatedObject
[ 36%] Built target AssociatedObject
Scanning dependencies of target AssociatedObject2
[ 37%] Building CXX object Test/CMakeFiles/AssociatedObject2.dir/AssociatedObject2.m.o
Linking C executable AssociatedObject2
[ 37%] Built target AssociatedObject2
Scanning dependencies of target AssociatedObject2_optimised
[ 38%] Building CXX object Test/CMakeFiles/AssociatedObject2_optimised.dir/AssociatedObject2.m.o
Linking C executable AssociatedObject2_optimised
[ 38%] Built target AssociatedObject2_optimised
Scanning dependencies of target AssociatedObject_optimised
[ 39%] Building CXX object Test/CMakeFiles/AssociatedObject_optimised.dir/AssociatedObject.m.o
Linking C executable AssociatedObject_optimised
[ 39%] Built target AssociatedObject_optimised
Scanning dependencies of target BlockImpTest
[ 40%] Building CXX object Test/CMakeFiles/BlockImpTest.dir/BlockImpTest.m.o
Linking C executable BlockImpTest
[ 40%] Built target BlockImpTest
Scanning dependencies of target BlockImpTest_optimised
[ 41%] Building CXX object Test/CMakeFiles/BlockImpTest_optimised.dir/BlockImpTest.m.o
Linking C executable BlockImpTest_optimised
[ 41%] Built target BlockImpTest_optimised
Scanning dependencies of target BlockTest_arc
[ 42%] Building CXX object Test/CMakeFiles/BlockTest_arc.dir/BlockTest_arc.m.o
[ 43%] Building CXX object Test/CMakeFiles/BlockTest_arc.dir/Test.m.o
Linking C executable BlockTest_arc
[ 43%] Built target BlockTest_arc
Scanning dependencies of target BlockTest_arc_optimised
[ 44%] Building CXX object Test/CMakeFiles/BlockTest_arc_optimised.dir/BlockTest_arc.m.o
[ 45%] Building CXX object Test/CMakeFiles/BlockTest_arc_optimised.dir/Test.m.o
Linking C executable BlockTest_arc_optimised
[ 45%] Built target BlockTest_arc_optimised
Scanning dependencies of target BoxedForeignException
[ 46%] Building CXX object Test/CMakeFiles/BoxedForeignException.dir/BoxedForeignException.m.o
Linking C executable BoxedForeignException
[ 46%] Built target BoxedForeignException
Scanning dependencies of target BoxedForeignException_optimised
[ 47%] Building CXX object Test/CMakeFiles/BoxedForeignException_optimised.dir/BoxedForeignException.m.o
Linking C executable BoxedForeignException_optimised
[ 47%] Built target BoxedForeignException_optimised
Scanning dependencies of target CXXExceptions
[ 48%] Building CXX object Test/CMakeFiles/CXXExceptions.dir/CXXException.m.o
[ 50%] Building CXX object Test/CMakeFiles/CXXExceptions.dir/CXXException.cc.o
Linking C executable CXXExceptions
[ 50%] Built target CXXExceptions
Scanning dependencies of target CXXExceptions_optimised
[ 51%] Building CXX object Test/CMakeFiles/CXXExceptions_optimised.dir/CXXException.m.o
[ 52%] Building CXX object Test/CMakeFiles/CXXExceptions_optimised.dir/CXXException.cc.o
Linking C executable CXXExceptions_optimised
[ 52%] Built target CXXExceptions_optimised
Scanning dependencies of target ExceptionTest
[ 53%] Building CXX object Test/CMakeFiles/ExceptionTest.dir/ExceptionTest.m.o
Linking C executable ExceptionTest
[ 53%] Built target ExceptionTest
Scanning dependencies of target ExceptionTest_optimised
[ 54%] Building CXX object Test/CMakeFiles/ExceptionTest_optimised.dir/ExceptionTest.m.o
Linking C executable ExceptionTest_optimised
[ 54%] Built target ExceptionTest_optimised
Scanning dependencies of target ForeignException
[ 55%] Building CXX object Test/CMakeFiles/ForeignException.dir/ForeignException.m.o
Linking C executable ForeignException
[ 55%] Built target ForeignException
Scanning dependencies of target ForeignException_optimised
[ 56%] Building CXX object Test/CMakeFiles/ForeignException_optimised.dir/ForeignException.m.o
Linking C executable ForeignException_optimised
[ 56%] Built target ForeignException_optimised
Scanning dependencies of target Forward
[ 57%] Building CXX object Test/CMakeFiles/Forward.dir/Forward.m.o
Linking C executable Forward
[ 57%] Built target Forward
Scanning dependencies of target Forward_optimised
[ 58%] Building CXX object Test/CMakeFiles/Forward_optimised.dir/Forward.m.o
Linking C executable Forward_optimised
[ 58%] Built target Forward_optimised
Scanning dependencies of target ManyManySelectors
[ 59%] Building CXX object Test/CMakeFiles/ManyManySelectors.dir/ManyManySelectors.m.o
Linking C executable ManyManySelectors
[ 59%] Built target ManyManySelectors
Scanning dependencies of target ManyManySelectors_optimised
[ 60%] Building CXX object Test/CMakeFiles/ManyManySelectors_optimised.dir/ManyManySelectors.m.o
Linking C executable ManyManySelectors_optimised
[ 60%] Built target ManyManySelectors_optimised
Scanning dependencies of target MethodArguments
[ 61%] Building CXX object Test/CMakeFiles/MethodArguments.dir/MethodArguments.m.o
Linking C executable MethodArguments
[ 61%] Built target MethodArguments
Scanning dependencies of target MethodArguments_optimised
[ 62%] Building CXX object Test/CMakeFiles/MethodArguments_optimised.dir/MethodArguments.m.o
Linking C executable MethodArguments_optimised
[ 62%] Built target MethodArguments_optimised
Scanning dependencies of target NestedExceptions
[ 63%] Building CXX object Test/CMakeFiles/NestedExceptions.dir/NestedExceptions.m.o
Linking C executable NestedExceptions
[ 63%] Built target NestedExceptions
Scanning dependencies of target NestedExceptions_optimised
[ 64%] Building CXX object Test/CMakeFiles/NestedExceptions_optimised.dir/NestedExceptions.m.o
Linking C executable NestedExceptions_optimised
[ 64%] Built target NestedExceptions_optimised
Scanning dependencies of target NilException
[ 65%] Building CXX object Test/CMakeFiles/NilException.dir/NilException.m.o
Linking C executable NilException
[ 65%] Built target NilException
Scanning dependencies of target NilException_optimised
[ 66%] Building CXX object Test/CMakeFiles/NilException_optimised.dir/NilException.m.o
Linking C executable NilException_optimised
[ 66%] Built target NilException_optimised
Scanning dependencies of target PropertyAttributeTest
[ 67%] Building CXX object Test/CMakeFiles/PropertyAttributeTest.dir/PropertyAttributeTest.m.o
Linking C executable PropertyAttributeTest
[ 67%] Built target PropertyAttributeTest
Scanning dependencies of target PropertyAttributeTest_optimised
[ 68%] Building CXX object Test/CMakeFiles/PropertyAttributeTest_optimised.dir/PropertyAttributeTest.m.o
Linking C executable PropertyAttributeTest_optimised
[ 68%] Built target PropertyAttributeTest_optimised
Scanning dependencies of target PropertyIntrospectionTest
[ 69%] Building CXX object Test/CMakeFiles/PropertyIntrospectionTest.dir/PropertyIntrospectionTest.m.o
Linking C executable PropertyIntrospectionTest
[ 69%] Built target PropertyIntrospectionTest
Scanning dependencies of target PropertyIntrospectionTest2_arc
[ 70%] Building CXX object Test/CMakeFiles/PropertyIntrospectionTest2_arc.dir/PropertyIntrospectionTest2_arc.m.o
<inline asm>:1:27: error: unexpected token in argument list
        mov     fp, fp          ; marker for objc_retainAutoreleaseReturnValue
                                             ^
<inline asm>:1:27: error: unexpected token in argument list
        mov     fp, fp          ; marker for objc_retainAutoreleaseReturnValue
                                             ^
<inline asm>:1:27: error: unexpected token in argument list
        mov     fp, fp          ; marker for objc_retainAutoreleaseReturnValue
                                             ^
<inline asm>:1:27: error: unexpected token in argument list
        mov     fp, fp          ; marker for objc_retainAutoreleaseReturnValue
                                             ^
<inline asm>:1:27: error: unexpected token in argument list
        mov     fp, fp          ; marker for objc_retainAutoreleaseReturnValue
                                             ^
5 errors generated.
Test/CMakeFiles/PropertyIntrospectionTest2_arc.dir/build.make:54: recipe for target 'Test/CMakeFiles/PropertyIntrospectionTest2_arc.dir/PropertyIntrospectionTest2_arc.m.o' failed
make[2]: *** [Test/CMakeFiles/PropertyIntrospectionTest2_arc.dir/PropertyIntrospectionTest2_arc.m.o] Error 1
CMakeFiles/Makefile2:1359: recipe for target 'Test/CMakeFiles/PropertyIntrospectionTest2_arc.dir/all' failed
make[1]: *** [Test/CMakeFiles/PropertyIntrospectionTest2_arc.dir/all] Error 2
Makefile:147: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by davidchisnall** [comment] 2015-12-31 09:31
This is a clang bug.  I've reported the issue upstream, hopefully it can be fixed in 3.8.

**Comment by plaurent** [comment] 2015-12-31 18:38
Could you provide a link to the filed issue so that I can monitor it and try to build clang on Aarch64 when it's fixed?

**Comment by davidchisnall** [comment] 2015-12-31 18:41
https://llvm.org/bugs/show_bug.cgi?id=25957 Feel free to follow up with more info.  I think Tim Northover is responsible for this breakage.

**Comment by GalenRhodes** [comment] 2016-03-30 17:38
As of version 3.9 (trunk from 03/15/2016) the issue is still there.

**Comment by GalenRhodes** [comment] 2016-03-30 17:55
Any idea what line in what file in the CLANG source I have to patch to make this work at least for myself?

**Comment by davidchisnall** [comment] 2016-03-30 18:13
Look in `clang/lib/CodeGen/TargetInfo.cpp`.  There's a method `AArch64TargetCodeGenInfo::getARCRetainAutoreleasedReturnValueMarker()`.  This should probably be conditional on targeting a Mac runtime, but if you just want something that works for now then simply making it return `nullptr` should work.

**Comment by GalenRhodes** [comment] 2016-03-30 18:14
Found it!  Awesome!  Thank you!!!!!

--
Galen Rhodes
galenrhodes@me.com

**Comment by davidchisnall** [comment] 2017-12-14 09:35
I believe that this is now fixed in clang.

**Closed by davidchisnall** 2017-12-14 09:35 UTC
