### ISSUE TITLE
valueForKey broken after upgrading libobjc2/gnustep-base/gnustep-make

### ISSUE THREAD

**Issue by dlobron** [gnustep/libobjc2#52] opened 2018-01-12 17:54 UTC
I've been working to get a large program running on Ubuntu Linux, with the clang compiler.  As part of this, I took the latest source for libobjc2, gnustep-base, and gnustep-make.  

After doing this, I found that the valueForKey is broken for a large class in one of my shared libraries.  The class is a subclass of NSObject, so it's using the valueForKey implementation from the runtime.

I confirmed with print statements that I'm assigning the ivars correctly, but I find that the valueForKey method returns the wrong ivar for a given key.  For example, I have two keys called "binary" and "argument", of type NSString* and NSArray*, respectively.  I assign to these variables directly in my main program.  I then attempt to print the variables in a loop, having stored their names in an array called _keys:

`- (void)debugKeyLoop
   {
     NSLog(@"DBG: Printing keys");
     for (NSString *key in _keys) {
       id v = [self valueForKey:key];
       NSLog(@"DBG: debug key loop, got val %@ for key %@, my class is %@",
             v, key, [[self class] description]);
     }
   }`

The object is called "config", and the code is:

config->binary = [NSString stringWithFormat:@"/bin/sh"];
config->argument = [[NSArray arrayWithObjects:@"-c", @"echo Child starting; sleep 10; echo Child exiting", nil] retain];
[config debugKeyLoop];

On the first iteration, the wrong value for the key "binary" is printed:

2018-01-12 17:42:53.026 MinRep[5192:5192] DBG: Printing keys
2018-01-12 17:42:53.026 MinRep[5192:5192] DBG: debug key loop, got val ("-c", "echo Child starting; sleep 10; echo Child exiting") for key binary, my class is SubprogramConfiguration

Note that the key "binary" is returning the NSArray value that was assigned to a different instance variable, "argument".  The next iteration of the loop throws a segmentation fault.

My code has been around for years, and previous versions of libobjc2/gnustep-base/gnustep-make did not exhibit this problem, which leads me to suspect a problem with the libobjc2 runtime.  I'm working on a minimal reproducer now.  So far, the minimal code has not reproduced the bug, but I figured I would open this ticket in case owners of the runtime code might have an idea of recent changes that could cause this.  If this turns out not to be reproducible or not in libobjc2, I will close this CR (I can't revert my gnustep-base and gnustep-make versions to the previous ones, because only the latest codelines are compatible).

**Comment by tedge** [comment] 2018-01-12 20:50
There was a discussion on the mailing list about a similar crash while accessing ivars on libobjc2; Please try applying the libobjc2 patch attached to this list message, and see if that fixes the problem:
http://lists.gnu.org/archive/html/discuss-gnustep/2017-12/msg00129.html

**Comment by davidchisnall** [comment] 2018-01-13 11:05
The root cause of this is that the work-around that I put into clang to try to allow code that mixed new and old ABIs to work together doesn't correctly work in all cases with the Linux run-time linker.  I think that the correct fix is simply to remove that code in clang.

**Comment by dlobron** [comment] 2018-01-16 22:47
Thanks,@davidchisnall and @tedge - pardon my slow reply.  I'm trying this now.  A few other parts of my build also broke, so my testing is stop-and-go.  I will plan to update here as soon as I have progress.

**Comment by dlobron** [comment] 2018-01-19 14:34
I can confirm that this patch fixed my issue.  Thanks very much!

David, would you like me to open a PR to apply the patch?  Or would you prefer to fix the code in clang, as you suggested above?  In the latter case, let me know if you'd like me to open a bug report on clang/llvm for this change or if you've already do so.  Once we do that, this bug can be closed.

**Comment by davidchisnall** [comment] 2018-01-19 14:46
I think that this only appears on Linux, as a result of specific behaviour of the Linux run-time linker, and the fix does not work well on other architectures (and breaks completely with static linking).  I think the best thing to do is fix this in clang, and keep the work-around for Linux systems.

**Comment by dlobron** [comment] 2018-01-19 14:49
Sounds good.  I will close this.

Do you have a bug report open on clang, or would you like me to file one?  Let me know if I can help at all with testing or development.

**Comment by davidchisnall** [comment] 2018-01-19 14:56
I don't have an open clang report, and it's probably the wrong place to file one, so I'll leave this open to remind me to fix it in clang.  The fix is simply to remove the guess and make the external reference have external linkage.

**Comment by davidchisnall** [comment] 2018-08-07 12:28
Fixed in llvm-project/clang@c023d882a7771431c28b1f93805e70b768589e4a

Hopefully this will be merged into the 7.0 release.

**Closed by davidchisnall** 2018-08-07 12:28 UTC
