### ISSUE TITLE
Make failing at "[10%] Linking C executable alias"

### ISSUE THREAD

**Issue by TostrStrudl** [gnustep/libobjc2#234] opened 2022-11-27 19:16 UTC
Hi guys. I saw an almost identical problem here on the page, but after trying to use the process they did, I'm still getting the error. It is:

"/usr/bin/ld: ../libobjc.so.4.6: undefined reference to 'std::__throw_length_error(char const*)'
 clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
 make[2]: *** [Test/CMakeFiles/alias.dir/build.make:102: Test/alias] Error 1
 make[1]: *** [CMakeFiles/Makefile2:604:  Test/CMakeFiles/alias.dir/all] Error 2"

I know it has something to do with my libraries (I've been trying for days to get GNUstep, libobjc2, LLVM and clang to compile together correctly), but I don't know the exact fix for this or how to execute said fix. Trying to enable the ARC capabilities as well. Any help would be appreciated. Thanks

**Comment by davidchisnall** [comment] 2022-11-28 09:35
This is probably caused by using headers from a version of libstdc++ that I haven't tested with.  Setting your C++ standard library as the C++ runtime to use should fix it.

**Comment by davidchisnall** [comment] 2023-01-31 16:41
What is your C++ standard library?  This might be fixed by some changes I made at the weekend.

**Comment by davidchisnall** [comment] 2023-02-19 16:12
This should be fixed by the recent CMake changes.

**Closed by davidchisnall** 2023-02-19 16:12 UTC
