### ISSUE TITLE
Can't be build on Cygwin x86

### ISSUE THREAD

**Issue by CNAmira** [gnustep/libobjc2#47] opened 2017-12-03 14:26 UTC
While I have set the CMAKE_C_COMPILER to clang, it reports that
```
[ 17%] Building C object CMakeFiles/objc.dir/sendmsg2.c.o
[ 18%] Building C object CMakeFiles/objc.dir/statics_loader.c.o
[ 18%] Building C object CMakeFiles/objc.dir/toydispatch.c.o
[ 19%] Building ASM object CMakeFiles/objc.dir/block_trampolines.S.o
clang-4.0: error: unsupported option '-fPIC' for target 'i686-pc-windows-cygnus'
clang-4.0: error: unsupported option '-fPIC' for target 'i686-pc-windows-cygnus'
make[2]: *** [CMakeFiles/objc.dir/build.make:591: CMakeFiles/objc.dir/block_trampolines.S.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/objc.dir/all] Error 2
make: *** [Makefile:161: all] Error 2
```
So I tried to remove `-fPIC` flag from flags.cmake, but it shown a link stage error as follow
```
[ 27%] Linking C shared library cygobjc-4.6.dll
CMakeFiles/objc.dir/properties.m.o:(.rdata+0x1d2): multiple definition of `.objc_sel_namecopy'
CMakeFiles/objc.dir/associate.m.o:(.rdata+0xa0): first defined here
/usr/lib/gcc/i686-pc-cygwin/6.4.0/../../../../i686-pc-cygwin/bin/ld: Cannot export objc_msgSend: symbol not defined
/usr/lib/gcc/i686-pc-cygwin/6.4.0/../../../../i686-pc-cygwin/bin/ld: Cannot export objc_msgSend_fpret: symbol not found
/usr/lib/gcc/i686-pc-cygwin/6.4.0/../../../../i686-pc-cygwin/bin/ld: Cannot export objc_msgSend_stret: symbol not found
/usr/lib/gcc/i686-pc-cygwin/6.4.0/../../../../i686-pc-cygwin/bin/ld: Error: 0-bit reloc in dll
/usr/lib/gcc/i686-pc-cygwin/6.4.0/../../../../i686-pc-cygwin/bin/ld: Error: 0-bit reloc in dll
/usr/lib/gcc/i686-pc-cygwin/6.4.0/../../../../i686-pc-cygwin/bin/ld: Error: 0-bit reloc in dll
CMakeFiles/objc.dir/block_to_imp.c.o:(.text+0xaa): undefined reference to `__objc_block_trampoline_end_sret'
CMakeFiles/objc.dir/block_to_imp.c.o:(.text+0xb0): undefined reference to `__objc_block_trampoline_sret'
CMakeFiles/objc.dir/block_to_imp.c.o:(.text+0xc1): undefined reference to `__objc_block_trampoline_end'
CMakeFiles/objc.dir/block_to_imp.c.o:(.text+0xc7): undefined reference to `__objc_block_trampoline'
CMakeFiles/objc.dir/objc_msgSend.S.o:(.text+0x72): undefined reference to `slowMsgLookup'
CMakeFiles/objc.dir/objc_msgSend.S.o:(.text+0x84): undefined reference to `GLOBAL_OFFSET_TABLE_'
CMakeFiles/objc.dir/objc_msgSend.S.o:(.text+0x8a): undefined reference to `SmallObjectClasses'
CMakeFiles/objc.dir/objc_msgSend.S.o:(.text+0x10a): undefined reference to `slowMsgLookup'
CMakeFiles/objc.dir/objc_msgSend.S.o:(.text+0x11c): undefined reference to `GLOBAL_OFFSET_TABLE_'
CMakeFiles/objc.dir/objc_msgSend.S.o:(.text+0x122): undefined reference to `SmallObjectClasses'
CMakeFiles/objc.dir/objc_msgSend.S.o:(.text+0x1a2): undefined reference to `slowMsgLookup'
CMakeFiles/objc.dir/objc_msgSend.S.o:(.text+0x1b4): undefined reference to `GLOBAL_OFFSET_TABLE_'
CMakeFiles/objc.dir/objc_msgSend.S.o:(.text+0x1ba): undefined reference to `SmallObjectClasses'
CMakeFiles/objc.dir/Protocol2.m.o:(.text+0xd3): undefined reference to `_imp____objc_exec_class'
CMakeFiles/objc.dir/arc.m.o:(.text+0x372): undefined reference to `objc_msgSend'
CMakeFiles/objc.dir/arc.m.o:(.text+0x582): undefined reference to `objc_msgSend'
CMakeFiles/objc.dir/arc.m.o:(.text+0x8e1): undefined reference to `objc_msgSend'
CMakeFiles/objc.dir/arc.m.o:(.text+0x8fe): undefined reference to `objc_msgSend'
CMakeFiles/objc.dir/arc.m.o:(.text+0xb60): undefined reference to `objc_msgSend'
CMakeFiles/objc.dir/arc.m.o:(.text+0x2553): undefined reference to `_imp____objc_exec_class'
CMakeFiles/objc.dir/associate.m.o:(.text+0x2ec): undefined reference to `objc_msgSend'
CMakeFiles/objc.dir/associate.m.o:(.text+0x1023): undefined reference to `_imp____objc_exec_class'
CMakeFiles/objc.dir/properties.m.o:(.text+0x26a): undefined reference to `objc_msgSend'
CMakeFiles/objc.dir/properties.m.o:(.text+0x299): undefined reference to `objc_msgSend'
CMakeFiles/objc.dir/properties.m.o:(.text+0x3f0): undefined reference to `objc_msgSend'
CMakeFiles/objc.dir/properties.m.o:(.text+0x4e8): undefined reference to `objc_msgSend'
CMakeFiles/objc.dir/properties.m.o:(.text+0x1f33): undefined reference to `_imp____objc_exec_class'
collect2: error: ld returned 1 exit status
clang-4.0: error: linker (via gcc) command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/objc.dir/build.make:859: cygobjc-4.6.dll] Error 1
make[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/objc.dir/all] Error 2
make: *** [Makefile:161: all] Error 2
```

**Comment by davidchisnall** [comment] 2017-12-08 11:16
I don't have a Windows machine to test this on, but it looks as if the relocations are wrong for Windows.

**Comment by CNAmira** [comment] 2017-12-08 11:24
Might it be a clang bug?

**Comment by davidchisnall** [comment] 2017-12-08 11:29
Most of the code is hand-written assembly, so it's probably my bug.  The `_imp____objc_exec_class` one is interesting though, as it seems to imply that `__objc_exec_class` is missing the dlexport attribute.

**Comment by davidchisnall** [comment] 2017-12-14 09:34
It would help if you can attach the assembly generated from a simple program that calls an external function and accesses a global variable on Windows.  For example:

`c

extern int foo;
extern int bar(void);

int fn(void)
{
  return foo + bar();
}
`

Please compile this with `clang -S -O1`.

**Comment by CNAmira** [comment] 2017-12-14 10:42
```
        .text
        .def     @feat.00;
        .scl    3;
        .type   0;
        .endef
        .globl  @feat.00
@feat.00 = 1
        .def     _fn;
        .scl    2;
        .type   32;
        .endef
        .globl  _fn
        .p2align        4, 0x90
_fn:                                    # @fn
# BB#0:
        pushl   %esi
        movl    _foo, %esi
        calll   _bar
        addl    %esi, %eax
        popl    %esi
        retl
```

**Comment by davidchisnall** [comment] 2017-12-14 10:44
Ah - on 32-bit Windows, DLLs aren't position independent and this code is assuming everything is.  Okay, that should be simple to fix...

**Comment by davidchisnall** [comment] 2017-12-14 13:22
Please can you try this patch and see if it fixes some of the errors?

```diff
diff --git a/objc_msgSend.x86-32.S b/objc_msgSend.x86-32.S
index 77193bd..0ca5333 100644
--- a/objc_msgSend.x86-32.S
+++ b/objc_msgSend.x86-32.S
@@ -1,3 +1,10 @@
+#if defined(__CYGWIN32__) || (defined(_WIN32) && !defined(_WIN64))
+#define PLT(x) x
+#define WINDOWS
+#else
+#define PLT(x) x@PLT
+#endif
+
 .macro MSGSEND receiver, sel, fpret
        .cfi_startproc                        
        movl  \receiver(%esp), %eax
@@ -54,7 +61,7 @@
        push  %ecx                           # _cmd
        push  %eax                           # &self
        .cfi_def_cfa_offset 12
-       call  slowMsgLookup@PLT
+       call  PLT(slowMsgLookup)
        add   $8, %esp                       # restore the stack
 
 
@@ -65,9 +72,13 @@
 7:
        popl  %ebx;
 8:
+#ifdef WINDOWS
+       mov   SmallObjectClasses, %eax
+#else
        addl  $_GLOBAL_OFFSET_TABLE_+(8b-7b), %ebx
        leal  SmallObjectClasses@GOTOFF(%ebx), %eax
        mov   (%eax), %eax
+#endif
        popl  %ebx
        jmp   1b 
        .cfi_endproc
```

**Comment by CNAmira** [comment] 2017-12-15 10:06
```
[ 19%] Linking C shared library cygobjc-4.6.dll
CMakeFiles/objc.dir/properties.m.o:(.rdata+0x2e1): multiple definition of `.objc_sel_namecopy'
CMakeFiles/objc.dir/associate.m.o:(.rdata+0xcd): first defined here
/usr/lib/gcc/i686-pc-cygwin/6.4.0/../../../../i686-pc-cygwin/bin/ld: Cannot export objc_msgSend: symbol not defined
/usr/lib/gcc/i686-pc-cygwin/6.4.0/../../../../i686-pc-cygwin/bin/ld: Cannot export objc_msgSend_fpret: symbol not found
/usr/lib/gcc/i686-pc-cygwin/6.4.0/../../../../i686-pc-cygwin/bin/ld: Cannot export objc_msgSend_stret: symbol not found
CMakeFiles/objc.dir/block_to_imp.c.o:(.text+0x8): undefined reference to `__objc_block_trampoline'
CMakeFiles/objc.dir/block_to_imp.c.o:(.text+0xd): undefined reference to `__objc_block_trampoline_end'
CMakeFiles/objc.dir/block_to_imp.c.o:(.text+0x5c): undefined reference to `__objc_block_trampoline_sret'
CMakeFiles/objc.dir/block_to_imp.c.o:(.text+0x61): undefined reference to `__objc_block_trampoline_end_sret'
CMakeFiles/objc.dir/block_to_imp.c.o:(.text+0x106): undefined reference to `__objc_block_trampoline_end_sret'
CMakeFiles/objc.dir/block_to_imp.c.o:(.text+0x10c): undefined reference to `__objc_block_trampoline_sret'
CMakeFiles/objc.dir/block_to_imp.c.o:(.text+0x13d): undefined reference to `__objc_block_trampoline_end'
CMakeFiles/objc.dir/block_to_imp.c.o:(.text+0x143): undefined reference to `__objc_block_trampoline'
CMakeFiles/objc.dir/objc_msgSend.S.o:(.text+0x54): undefined reference to `slowMsgLookup'
CMakeFiles/objc.dir/objc_msgSend.S.o:(.text+0x65): undefined reference to `SmallObjectClasses'
CMakeFiles/objc.dir/objc_msgSend.S.o:(.text+0xc2): undefined reference to `slowMsgLookup'
CMakeFiles/objc.dir/objc_msgSend.S.o:(.text+0xd3): undefined reference to `SmallObjectClasses'
CMakeFiles/objc.dir/objc_msgSend.S.o:(.text+0x130): undefined reference to `slowMsgLookup'
CMakeFiles/objc.dir/objc_msgSend.S.o:(.text+0x141): undefined reference to `SmallObjectClasses'
CMakeFiles/objc.dir/Protocol2.m.o:(.text+0xd3): undefined reference to `_imp____objc_exec_class'
CMakeFiles/objc.dir/arc.m.o:(.text+0x372): undefined reference to `objc_msgSend'
CMakeFiles/objc.dir/arc.m.o:(.text+0x582): undefined reference to `objc_msgSend'
CMakeFiles/objc.dir/arc.m.o:(.text+0x8e1): undefined reference to `objc_msgSend'
CMakeFiles/objc.dir/arc.m.o:(.text+0x8fe): undefined reference to `objc_msgSend'
CMakeFiles/objc.dir/arc.m.o:(.text+0xb60): undefined reference to `objc_msgSend'
CMakeFiles/objc.dir/arc.m.o:(.text+0x2603): undefined reference to `_imp____objc_exec_class'
CMakeFiles/objc.dir/associate.m.o:(.text+0x2ec): undefined reference to `objc_msgSend'
CMakeFiles/objc.dir/associate.m.o:(.text+0x11e3): undefined reference to `_imp____objc_exec_class'
CMakeFiles/objc.dir/properties.m.o:(.text+0x26a): undefined reference to `objc_msgSend'
CMakeFiles/objc.dir/properties.m.o:(.text+0x299): undefined reference to `objc_msgSend'
CMakeFiles/objc.dir/properties.m.o:(.text+0x3f0): undefined reference to `objc_msgSend'
CMakeFiles/objc.dir/properties.m.o:(.text+0x4e8): undefined reference to `objc_msgSend'
CMakeFiles/objc.dir/properties.m.o:(.text+0x1c83): undefined reference to `_imp____objc_exec_class'
collect2: error: ld returned 1 exit status
clang-4.0: error: linker (via gcc) command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/objc.dir/build.make:859: cygobjc-4.6.dll] Error 1
make[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/objc.dir/all] Error 2
make: *** [Makefile:161: all] Error 2
```

**Comment by davidchisnall** [comment] 2017-12-15 10:30
```
CMakeFiles/objc.dir/objc_msgSend.S.o:(.text+0x54): undefined reference to `slowMsgLookup'
CMakeFiles/objc.dir/objc_msgSend.S.o:(.text+0x65): undefined reference to `SmallObjectClasses'
```

I think these can be fixed by wrapping all references to these symbols in `objc_msgSend.x86-32.S` with `CDECL()`.


```
Cannot export objc_msgSend: symbol not defined
``` 

I think this is probably the cause of most of these.  We are probably missing some `.def` directives for the exported functions.  Can you try adding something like this:

```asm
	.def	 CDECL(objc_msgSend);
	.scl	2;
	.type	32;
	.endef
```

And let me know if that improves things?

```
CMakeFiles/objc.dir/block_to_imp.c.o:(.text+0x10c): undefined reference to `__objc_block_trampoline_sret'
```

These probably have the same cause as above.

```
CMakeFiles/objc.dir/properties.m.o:(.text+0x1c83): undefined reference to `_imp____objc_exec_class'
```

I believe that this is caused by clang implciitly adding dllimport to `__objc_exec_class`, on the assumption that it's provided by a different library.  We can probably fudge that by declaring a function `imp____objc_exec_class` that simple calls `___objc_exec_class`.

**Comment by CNAmira** [comment] 2017-12-15 10:42
No, it doesn't improve anything.

**Comment by davidchisnall** [comment] 2017-12-15 10:42
Can you paste the patch that you used to test?

**Comment by CNAmira** [comment] 2017-12-15 10:44
```diff
diff --git a/objc_msgSend.x86-32.S b/objc_msgSend.x86-32.S
index 77193bd..006ceef 100644
--- a/objc_msgSend.x86-32.S
+++ b/objc_msgSend.x86-32.S
@@ -1,3 +1,10 @@
+#if defined(__CYGWIN32__) || (defined(_WIN32) && !defined(_WIN64))
+#define PLT(x) x
+#define WINDOWS
+#else
+#define PLT(x) x@PLT
+#endif
+
 .macro MSGSEND receiver, sel, fpret
        .cfi_startproc
        movl  \receiver(%esp), %eax
@@ -54,7 +61,7 @@
        push  %ecx                           # _cmd
        push  %eax                           # &self
        .cfi_def_cfa_offset 12
-       call  slowMsgLookup@PLT
+       call  PLT(slowMsgLookup)
        add   $8, %esp                       # restore the stack


@@ -65,9 +72,13 @@
 7:
        popl  %ebx;
 8:
+#ifdef WINDOWS
+        mov   SmallObjectClasses, %eax
+#else
        addl  $_GLOBAL_OFFSET_TABLE_+(8b-7b), %ebx
        leal  SmallObjectClasses@GOTOFF(%ebx), %eax
        mov   (%eax), %eax
+#endif
        popl  %ebx
        jmp   1b
        .cfi_endproc
@@ -84,3 +95,7 @@ CDECL(objc_msgSend):
 TYPE_DIRECTIVE(CDECL(objc_msgSend_stret), @function)
 CDECL(objc_msgSend_stret):
        MSGSEND 8, 12, 0
+.def    CDECL(objc_msgSend);
+       .scl    2;
+       .type   32;
+       .endef
```

**Comment by davidchisnall** [comment] 2017-12-15 10:59
I think the `.def` needs to come  before the definition of `objc_msgSend`

**Comment by CNAmira** [comment] 2017-12-15 11:03
Why the libobjc bundled in 'official' GNUstep works well?

**Comment by davidchisnall** [comment] 2017-12-15 11:10
Define 'works well' - it's the ancient GCC runtime, which doesn't support ARC, or most of the features of modern Objective-C.

**Comment by CNAmira** [comment] 2017-12-15 11:12
Oh I'm sorry I don't know that.

**Comment by CNAmira** [comment] 2018-03-04 15:36
I found that clang will reference to `__imp____objc_exec_class` symbol when compile objc codes on windows platforms, maybe some hacks could solve these problems.

**Comment by davidchisnall** [comment] 2018-08-02 08:43
I'm not sure if it helps with Cygwin, but it is now possible to build libobjc2 as a native Windows binary with clang and this under-review patch: https://reviews.llvm.org/D50144

Only the new ABI is supported, so you will need to compile everything else with -fobjc-runtime=gnustep-2.0.

**Comment by CNAmira** [comment] 2018-08-05 09:48
I use a trunk version of clang with the patch applied.
```
$ clang-8 --version
clang version 8.0.0 (trunk 338954) (llvm/trunk 338953)
Target: i686-pc-windows-cygnus
Thread model: posix
InstalledDir: /usr/bin
```
However it doesn't fix the problem.
```
$ LANG=en_US.utf8 make
[  0%] Linking C shared library cygobjc-4.6.dll
CMakeFiles/objc.dir/block_to_imp.c.o:(.text+0x7): undefined reference to `__objc_block_trampoline'
CMakeFiles/objc.dir/block_to_imp.c.o:(.text+0xc): undefined reference to `__objc_block_trampoline_end'
CMakeFiles/objc.dir/block_to_imp.c.o:(.text+0x53): undefined reference to `__objc_block_trampoline_sret'
CMakeFiles/objc.dir/block_to_imp.c.o:(.text+0x58): undefined reference to `__objc_block_trampoline_end_sret'
CMakeFiles/objc.dir/block_to_imp.c.o:(.text+0xff): undefined reference to `__objc_block_trampoline_sret'
CMakeFiles/objc.dir/block_to_imp.c.o:(.text+0x108): undefined reference to `__objc_block_trampoline_end_sret'
CMakeFiles/objc.dir/block_to_imp.c.o:(.text+0x136): undefined reference to `__objc_block_trampoline'
CMakeFiles/objc.dir/block_to_imp.c.o:(.text+0x13f): undefined reference to `__objc_block_trampoline_end'
CMakeFiles/objc.dir/objc_msgSend.S.o:(.text+0x53): undefined reference to `slowMsgLookup'
CMakeFiles/objc.dir/objc_msgSend.S.o:(.text+0x65): undefined reference to `SmallObjectClasses'
CMakeFiles/objc.dir/objc_msgSend.S.o:(.text+0xc3): undefined reference to `slowMsgLookup'
CMakeFiles/objc.dir/objc_msgSend.S.o:(.text+0xd5): undefined reference to `SmallObjectClasses'
CMakeFiles/objc.dir/objc_msgSend.S.o:(.text+0x133): undefined reference to `slowMsgLookup'
CMakeFiles/objc.dir/objc_msgSend.S.o:(.text+0x145): undefined reference to `SmallObjectClasses'
CMakeFiles/objc.dir/NSBlocks.m.o:(.text[_.objcv2_load_function]+0xc): undefined reference to `_imp____objc_load'
CMakeFiles/objc.dir/arc.m.o:(.text+0x3e0): undefined reference to `objc_msgSend'
CMakeFiles/objc.dir/arc.m.o:(.text+0x73f): undefined reference to `objc_msgSend'
CMakeFiles/objc.dir/arc.m.o:(.text+0x924): undefined reference to `objc_msgSend'
CMakeFiles/objc.dir/arc.m.o:(.text+0xc8f): undefined reference to `objc_msgSend'
CMakeFiles/objc.dir/arc.m.o:(.text+0xf16): undefined reference to `objc_msgSend'
CMakeFiles/objc.dir/associate.m.o:(.text+0x2ed): more undefined references to `objc_msgSend' follow
CMakeFiles/objc.dir/associate.m.o:(.text+0x48f): undefined reference to `_imp__objc_exception_rethrow'
CMakeFiles/objc.dir/associate.m.o:(.text+0x4ec): undefined reference to `_imp__objc_begin_catch'
CMakeFiles/objc.dir/associate.m.o:(.text+0x51f): undefined reference to `_imp__objc_end_catch'
CMakeFiles/objc.dir/properties.m.o:(.text+0x264): undefined reference to `objc_msgSend'
CMakeFiles/objc.dir/properties.m.o:(.text+0x293): undefined reference to `objc_msgSend'
CMakeFiles/objc.dir/properties.m.o:(.text+0x3f1): undefined reference to `objc_msgSend'
CMakeFiles/objc.dir/properties.m.o:(.text+0x4e9): undefined reference to `objc_msgSend'
collect2: error: ld returned 1 exit status
clang-8: error: linker (via gcc) command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/objc.dir/build.make:833: cygobjc-4.6.dll] Error 1
make[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/objc.dir/all] Error 2
make: *** [Makefile:161: all] Error 2
```

**Comment by davidchisnall** [comment] 2018-08-07 12:32
You have two issues:

1. You're using a released version of clang.  The clang changes to support the v2 ABI aren't yet in a release (see: https://reviews.llvm.org/D50144) and without them you will get references to non-existent symbols for exception handling (e.g. `__objc_begin_catch`).  With the clang patch, you should see these go away.
2. It appears that the assembly files are not being built.  I have only tried building on Windows with the Visual Studio (msbuild) generator.  I had to add some work-arounds to compile them and it appears that they aren't working for you.

Can Cygwin use normal Windows DLLs?  If so, it's probably easier to build the runtime outside of Cygwin and just use it as any other DLL.

**Comment by CNAmira** [comment] 2018-08-07 14:06
No, I'm using trunk version with the patch applied, not the "vanilla" clang.
Cygwin can use normal Windows DLLs, the ABI it used is same as MinGW.

**Comment by davidchisnall** [comment] 2019-03-29 09:19
Closing this.  For Cygwin, I recommend building as a native Windows binary and just using it from Cygwin.  There are still some outstanding clang patches to make multi-DLL Objective-C projects build with clang, but I hope to land them this weekend.

We now have CI on Windows, so I consider it a fully supported platform by the runtime.

**Closed by davidchisnall** 2019-03-29 09:19 UTC
